### ISSUE TITLE
1.16.2 JoinItems not working 

### ISSUE THREAD

**Issue by WolverStones** [ItsLewizzz/DeluxeHub#12]
In the latest version https://github.com/ItsLewizzz/DeluxeHub/pull/9, join items are broken. I won't get anything after connecting. I didn't see any error.

My config: https://hastebin.com/ewexayoqag.bash

This server is running Paper version git-Paper-162 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

**Comment by ItsLewizzz** [comment]
Hastebin has expired, can you send the error you're getting?

**Comment by WolverStones** [comment]
New config link: https://pastebin.com/k03pCgXN 
When connecting I did not see the mistake even after

**Comment by Qmegali** [comment]
I also have this issue. Could someone figure out how to resolve it?

**Comment by WolverStones** [comment]
> I also have this issue. Could someone figure out how to resolve it? For me, the custom items only appear on plugin refresh and not when the player enters the server.


I still have a problem, so far I've solved it by giving deluxehub reload when connecting a player, it's a stupid solution but it works: D

**Comment by osc1997** [comment]
I also had this issue, it is caused by the "clear_inventory" join setting. I assume that it's clearing the players inventory after the join items have been given to the player unlike in previous versions where their inventory would be cleared before the join items are given to the player.
