### ISSUE TITLE
Update to 1.21.1

### ISSUE THREAD

**Issue by BeholdIsLost** [ItsLewizzz/DeluxeHub#124]
I get a error with [19:45:07] [Server thread/ERROR]: Error occurred while enabling DeluxeHub v3.5.4 (Is it up to date?)
java.lang.ExceptionInInitializerError: null

[19:45:07] [Server thread/ERROR]: [DeluxeHub] There was an error unloading the VANISH module.
[19:45:07] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Set.forEach(java.util.function.Consumer)" because "this.holograms" is null

Thank you

**Comment by TutorialMan7727** [comment]
#125 should fix

**Comment by Strafbefehl** [comment]
Check this out :)
https://github.com/Strafbefehl/DeluxeHubReloaded/releases/tag/Release

**Comment by TutorialMan7727** [comment]
@Strafbefehl there is no issue tab on this new repo

**Comment by Strafbefehl** [comment]
> @Strafbefehl there is no issue tab on this new repo

Thanks I added the issue tab to it

**Comment by SliderKP** [comment]
> Check this out :) https://github.com/Strafbefehl/DeluxeHubReloaded/releases/tag/Release

thanks for updating bro !

**Comment by Strafbefehl** [comment]
> thanks for updating bro !

You're welcome :)
