### ISSUE TITLE
"disable_weather_change" option affect any worlds even if i set them as "disabled-worlds" in config.yml

### ISSUE THREAD

**Issue by D3monX** [ItsLewizzz/DeluxeHub#14]
As title, in config.yml i set some worlds as disabled-worlds, and disable_weather_change:true but it still affect any worlds in the server, even the disabled ones.

....config.yml...
.
.
.
# List any worlds you don't want DeluxeHub to manage.
disabled-worlds:
  # Should we invert the list making it a whitelist rather than a blacklist?
  invert: false
  # List your worlds here, set "worlds: {}" to disable
  worlds:
    - bskyblock_world
    - bskyblock_world_nether
.
.
.
  # Misc
  disable_weather_change: false
.
.

Note; all the others function only work in the enabled world as expected...

**Comment by ItsLewizzz** [comment]
Fixed in v3.4.0
