### ISSUE TITLE
Kit-pvp plugin and deluxe hub with pvp commands and permissions

### ISSUE THREAD

**Issue by ImaJamiroquai** [ItsLewizzz/DeluxeHub#5]
Hi ItsLewizzz! I'm teaching myself how to make a minecraft server and i've been using your plugin for my hub management. So far,i it has been great, but i just discovered one issue:

I have 2 servers connected with BungeeCord, one is the lobby and the other one is a kitpvp arena, i use in both servers your plugin. In the kitpvp server i use it to return to the lobby, but what happens is when i wanted to fight with other players it said [Deluxe Hub] Pvp is not allowed or something like that, so, my question is... is there a way that i can disable that command in the kitpvp server? so the kit-pvp plugin can control the pvp permissions.

Sorry for my english grammar and for my ignorance 

Thank you

**Comment by ItsLewizzz** [comment]
You can set disabled worlds in the DeluxeHub config (at the top) for DH to not manage.

**Comment by ImaJamiroquai** [comment]
Thank you very much! It worked :DDDDD
