### ISSUE TITLE
Requesting for permit

### ISSUE THREAD

**Issue by wxkj123** [ItsLewizzz/DeluxeHub#65]
Hello, ItsLewizzz, 
       What a fantastic plugin it is!!! You know I'm seeking this kind of plugin for a long time and here is it! I'm a Chinese server owner using your plugin, it helps me a lot! And players all like it! 
       Can I advertise this wonderful plugin to MCBBS, which is the largest Minecraft forum in China? Many server owners are seeking good plugins there. I'll translate the config files into Chinese and teach people how to use it there, let more people know it. I'll NEVER claim it as mine, I just wanna translate it and let more people know it. 
       Anticipating your early reply!

**Comment by xqwtxon** [comment]
I gonna implement translations. In that way we can change languages or create your own plugin messages...
