### ISSUE TITLE
Unable to remove lobby

### ISSUE THREAD

**Issue by MrKusta** [ItsLewizzz/DeluxeHub#75]
I was testing all functions of deluxehub and /setlobby to  set a lobby for my server.However most players claimed they don't want to be forced to born in the lobby.The issue occurred when I tried to remove the lobby.There is no command to remove the lobby or to turn off the lobby function.I edited the /plugin/DeluxeHub/data.yml to removed the content that defines the location of the lobby and /deluxehub reload to refresh settings.But the lobby still exists,after reloading deluxehub,even though I restarted the server.
Is there a command to remove this function completely? Otherwise what should I do to remove the lobby?I suggest that it should be added if there's no way.

**Comment by xqwtxon** [comment]
remove the config :3

**Comment by xqwtxon** [comment]
Also a good idea, so i created pull request...

**Comment by MrKusta** [comment]
> 

It worked.

And by overwriting the new-generated files with the old config files in which the content of 'spawn' had been removed,all former functions such as tablist and holographics have been recovered.

This is an useful suggestion.Hope to see the function to remove lobby in next release. =)
